### PR TITLE
FAQ link is invalid since redirect of wiki plugin page

### LINKED ISSUE #144: FAQ link is invalid since redirect of wiki plugin page
**Describe the bug**
FAQ link with further information about caught COM exception in the console log is not working anymore (plugin page not found).

**To Reproduce**
Cause any COM exception (e.g. exceeded timeout) printing following message in the console log: 
`For further information see FAQ: https://wiki.jenkins-ci.org/x/joLtB#TraceTronicECU-TESTPlugin-FAQ` 

**Expected behavior**
Link to GitHub instead: [FAQ](https://github.com/jenkinsci/ecutest-plugin#faq)

**Versions**
- Jenkins: unrelated
- Plugin: 2.13
- ECU-TEST: unrelated
- TEST-GUIDE: unrelated

**Additional context**
Initially caused by automatic redirect of Jenkins wiki links to Jenkins plugin site (see  [discussion](https://groups.google.com/forum/#!topic/jenkinsci-dev/EmBEZobmCFY)).

### PR DESCRIPTION
**Pull request by cpoenisch**
Fixes #144

### CODE REVIEW

File: src/main/java/de/tracetronic/jenkins/plugins/ecutest/log/TTConsoleLogger.java [hunk 1]
```diff
@@ -87,7 +87,7 @@ public void logComException(final Exception exception) {
         logError(String
             .format("Caught ComException: %s%n"
                     + "For further information see FAQ: "
-                    + "https://wiki.jenkins-ci.org/x/joLtB#TraceTronicECU-TESTPlugin-FAQ",
+                    + "https://github.com/jenkinsci/ecutest-plugin#faq",
```
Comment (JanGu-TT) [inline src/main/java/de/tracetronic/jenkins/plugins/ecutest/log/TTConsoleLogger.java]: May be add also link to debugging section? https://github.com/jenkinsci/ecutest-plugin#debugging
