### PR TITLE
First configured parameter is always used in the freestyle job

### LINKED ISSUE #165: First configured parameter is always used in the freestyle job
**Describe the bug**
When creating a Freestyle Job and using the ECU Test Plugin "Start ECU Test (parameterized)" the first parameter set is always used. If a different version is set for another run, it will be ignored.

**To Reproduce**
- create FreestyleJob and start ECU Test parameterized and choose a version
- start a second job with another Version parameterized

**Expected behavior**
Always use the configured parameter

**Versions**
- Jenkins: *
- Plugin: *
- ECU-TEST: *
- TEST-GUIDE: *

### PR DESCRIPTION
**Pull request by MartinGroscheTT**
Fixes #165

### CODE REVIEW

File: src/main/java/de/tracetronic/jenkins/plugins/ecutest/report/AbstractToolPublisher.java [hunk 1]
```diff
@@ -129,4 +129,19 @@ protected ETInstallation configureToolInstallation(final Computer computer,
...
+
+    /**
+     * Verify the installation object and updates properties if needed.
+     *
+     * @param envVars the environment variables of the run
+     */
+    public boolean isInstallationVerified(final EnvVars envVars) {
+        if (getInstallation() == null) {
+            return false;
+        }else if (!getInstallation().getName().equals(envVars.expand(getToolName()))) {
```
Comment (cpoenisch) [inline src/main/java/de/tracetronic/jenkins/plugins/ecutest/report/AbstractToolPublisher.java:141]: missing whitespace

File: src/main/java/de/tracetronic/jenkins/plugins/ecutest/tool/StartETBuilder.java [hunk 2]
```diff
@@ -155,13 +155,13 @@ public void performTool(final Run<?, ?> run, final FilePath workspace, final Lau
                 ETLogPublisher.RunListenerImpl.onStarted(expSettingsPath, listener);
             }
 
-            // Get selected ECU-TEST installation
-            if (getInstallation() == null) {
+            // verify selected ECU-Test installation
```
Comment (cpoenisch) [inline src/main/java/de/tracetronic/jenkins/plugins/ecutest/tool/StartETBuilder.java:158]: Start uppercase, ECU-TEST

File: src/main/java/de/tracetronic/jenkins/plugins/ecutest/tool/StopETBuilder.java [hunk 3]
```diff
@@ -49,9 +49,9 @@ public int getDefaultTimeout() {
     @Override
     public void performTool(final Run<?, ?> run, final FilePath workspace, final Launcher launcher,
                             final TaskListener listener) throws InterruptedException, IOException, ETPluginException {
-        // Get selected ECU-TEST installation
+        // verify selected ECU-TEST installation
```
Comment (cpoenisch) [inline src/main/java/de/tracetronic/jenkins/plugins/ecutest/tool/StopETBuilder.java:52]: see above
